### ISSUE TITLE
How to use the streamlit theme for Login and Logout button? 

### ISSUE THREAD

**Issue by vpatel289** [mstaal/msal_streamlit_authentication#4]
Hi Great component, 

How to change the login and Logout button theme based on streamlit theme using the newer version you released? 

Thanks!

**Comment by mstaal** [comment]
Hi @vpatel289 !
My idea was to allow one to style the buttons using CSS by e.g. setting a class selector on the button and then let the button inherit stylings associated with the selector. But I think I made a (non-critical) mistake in my initial bootstrap of the project I made in that it comes with some hardcoded CSS for the button, which I will soon remove. I have come to realize that it is causing people styling issues. To be frank, I will have to do some manual testing to see how to come about this easily since styling was not my main concern during the initial development.
